apiVersion: k3d.io/v1alpha2
kind: Simple
name: flux
servers: 1
agents: 0
image: rancher/k3s:v1.21.3-k3s1
registries:
  create: false
options:
  k3d:
    wait: true
    timeout: "240s"
    disableLoadbalancer: true
    disableImageVolume: false
    disableRollback: false
    disableHostIPInjection: false
  k3s:
    extraServerArgs: []
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
